[package]
name = "zenith"
version = "0.1.1"
authors = ["Amelia Clarke <amelia.amok@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8"

[dependencies.bevy]
features = ["dynamic", "wav"]
version = "0.5"
